-- MySQL Script generated by MySQL Workbench
-- dom 23 fev 2020 15:45:48 WET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema myfin
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema myfin
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `myfin` DEFAULT CHARACTER SET utf8 ;
USE `myfin` ;

-- -----------------------------------------------------
-- Table `myfin`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myfin`.`users` (
  `user_id` BIGINT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` TEXT(128) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `sessionkey` TEXT(128) NULL,
  `sessionkey_mobile` TEXT(128) NULL,
  `trustlimit` INT NULL,
  `trustlimit_mobile` INT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `myfin`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myfin`.`categories` (
  `category_id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `type` CHAR NOT NULL,
  `users_user_id` BIGINT NOT NULL,
  `description` MEDIUMTEXT NULL,
  PRIMARY KEY (`category_id`),
  INDEX `fk_category_users_idx` (`users_user_id` ASC),
  UNIQUE INDEX `uq_name_type_user_id` (`users_user_id` ASC, `type` ASC, `name` ASC),
  CONSTRAINT `fk_category_users`
    FOREIGN KEY (`users_user_id`)
    REFERENCES `myfin`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `myfin`.`accounts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myfin`.`accounts` (
  `account_id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  `description` MEDIUMTEXT NULL,
  `exclude_from_budgets` TINYINT(1) NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  `users_user_id` BIGINT NOT NULL,
  PRIMARY KEY (`account_id`),
  UNIQUE INDEX `account_id_UNIQUE` (`account_id` ASC),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC),
  INDEX `fk_accounts_users1_idx` (`users_user_id` ASC),
  CONSTRAINT `fk_accounts_users1`
    FOREIGN KEY (`users_user_id`)
    REFERENCES `myfin`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `myfin`.`balances`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myfin`.`balances` (
  `balance_id` BIGINT NOT NULL AUTO_INCREMENT,
  `date_timestamp` BIGINT NOT NULL,
  `amount` DOUBLE NOT NULL,
  `accounts_account_id` BIGINT NOT NULL,
  PRIMARY KEY (`balance_id`),
  INDEX `fk_balances_accounts1_idx` (`accounts_account_id` ASC),
  CONSTRAINT `fk_balances_accounts1`
    FOREIGN KEY (`accounts_account_id`)
    REFERENCES `myfin`.`accounts` (`account_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myfin`.`entities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myfin`.`entities` (
  `entity_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `users_user_id` BIGINT NOT NULL,
  PRIMARY KEY (`entity_id`),
  UNIQUE INDEX `entity_id_UNIQUE` (`entity_id` ASC),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC),
  INDEX `fk_entities_users1_idx` (`users_user_id` ASC),
  CONSTRAINT `fk_entities_users1`
    FOREIGN KEY (`users_user_id`)
    REFERENCES `myfin`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `myfin`.`transactions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myfin`.`transactions` (
  `transaction_id` BIGINT NOT NULL AUTO_INCREMENT,
  `date_timestamp` BIGINT NOT NULL,
  `amount` DOUBLE NOT NULL,
  `type` CHAR NOT NULL,
  `description` MEDIUMTEXT NULL,
  `entities_entity_id` INT NULL,
  `accounts_account_from_id` BIGINT NOT NULL,
  `accounts_account_to_id` BIGINT NULL,
  `categories_category_id` BIGINT NOT NULL,
  PRIMARY KEY (`transaction_id`),
  UNIQUE INDEX `transaction_id_UNIQUE` (`transaction_id` ASC),
  INDEX `fk_transactions_entities2_idx` (`entities_entity_id` ASC),
  INDEX `fk_transactions_accounts1_idx` (`accounts_account_from_id` ASC),
  INDEX `fk_transactions_accounts2_idx` (`accounts_account_to_id` ASC),
  INDEX `fk_transactions_categories1_idx` (`categories_category_id` ASC),
  CONSTRAINT `fk_transactions_entities2`
    FOREIGN KEY (`entities_entity_id`)
    REFERENCES `myfin`.`entities` (`entity_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_transactions_accounts1`
    FOREIGN KEY (`accounts_account_from_id`)
    REFERENCES `myfin`.`accounts` (`account_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_transactions_accounts2`
    FOREIGN KEY (`accounts_account_to_id`)
    REFERENCES `myfin`.`accounts` (`account_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_transactions_categories1`
    FOREIGN KEY (`categories_category_id`)
    REFERENCES `myfin`.`categories` (`category_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
