<?php

/* CONSTANTS */
const DEFAULT_SOMETHING = "DEFAULT";

const DEFAULT_CATEGORY_CREDIT_TAG = "C";
const DEFAULT_CATEGORY_DEBIT_TAG = "D";
const DEFAULT_CATEGORY_ACTIVE_STATUS = "Ativa";
const DEFAULT_CATEGORY_INACTIVE_STATUS = "Inativa";

const DEFAULT_ACCOUNT_ACTIVE_STATUS = "Ativa";
const DEFAULT_ACCOUNT_INACTIVE_STATUS = "Inativa";

const DEFAULT_TYPE_INCOME_TAG = "I";
const DEFAULT_TYPE_EXPENSE_TAG = "E";
const DEFAULT_TYPE_TRANSFER_TAG = "T";

/* RULES - auto-categorization */
const DEFAULT_RULES_OPERATOR_IGNORE = "IG";
const DEFAULT_RULES_OPERATOR_EQUALS = "EQ";
const DEFAULT_RULES_OPERATOR_NOT_EQUALS = "NEQ";
const DEFAULT_RULES_OPERATOR_CONTAINS = "CONTAINS";
const DEFAULT_RULES_OPERATOR_NOT_CONTAINS = "NOTCONTAINS";

/* ASSETS - types */
const DEFAULT_ASSETS_TYPE_PPR = "ppr";
const DEFAULT_ASSETS_TYPE_ETF = "etf";
const DEFAULT_ASSETS_TYPE_CRYPTO = "crypto";
const DEFAULT_ASSETS_TYPE_FIXED_INCOME = "fixed";
const DEFAULT_ASSETS_TYPE_INDEX_FUNDS = "index";
const DEFAULT_ASSETS_TYPE_INVESTMENT_FUNDS = "if";
const DEFAULT_ASSETS_TYPE_P2P = "p2p";
const DEFAULT_ASSETS_TYPE_STOCKS = "stock";

/* INVESTMENT TRANSACTIONS - types */
const DEFAULT_INVESTING_TRANSACTIONS_BUY = "B";
const DEFAULT_INVESTING_TRANSACTIONS_SELL = "S";

/* ACCOUNT TYPES */
const DEFAULT_ACCOUNT_TYPE_CURRENT_ACCOUNT = "CHEAC";
const DEFAULT_ACCOUNT_TYPE_SAVINGS_ACCOUNT = "SAVAC";
const DEFAULT_ACCOUNT_TYPE_INVESTMENT_ACCOUNT = "INVAC";
const DEFAULT_ACCOUNT_TYPE_CREDIT_ACCOUNT = "CREAC";
const DEFAULT_ACCOUNT_TYPE_MEAL_ACCOUNT = "MEALAC";
const DEFAULT_ACCOUNT_TYPE_WALLET = "WALLET";
const DEFAULT_ACCOUNT_TYPE_OTHER_ACCOUNT = "OTHAC";

const DEFAULT_TRANSACTIONS_FETCH_LIMIT = 99999;
