<?php

/* CONSTANTS */
define("DEFAULT_SOMETHING", "DEFAULT");

define("DEFAULT_CATEGORY_CREDIT_TAG", "C");
define("DEFAULT_CATEGORY_DEBIT_TAG", "D");
define("DEFAULT_ACCOUNT_ACTIVE_STATUS", "Ativa");
