FROM node:20-alpine AS build

WORKDIR /app

COPY package*.json .
RUN npm ci
COPY . .
ENV VITE_MYFIN_BASE_API_URL=/api
RUN npm run build

FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
COPY docker-entrypoint.sh .
EXPOSE 80
ENTRYPOINT [ "/docker-entrypoint.sh" ]
