import {
  AccountBalance,
  AccountBalanceWallet,
  Apartment,
  Build,
  CardGiftcard,
  Category as CategoryIconGlyph,
  Checkroom,
  ChildCare,
  CreditCard,
  DirectionsCar,
  Fastfood,
  FitnessCenter,
  Flight,
  Gavel,
  Home,
  HomeRepairService,
  Hotel,
  LocalCafe,
  LocalGasStation,
  LocalGroceryStore,
  LocalHospital,
  LocalParking,
  LocalPharmacy,
  Movie,
  MusicNote,
  Pets,
  Phone,
  ReceiptLong,
  Restaurant,
  School,
  ShoppingCart,
  SportsEsports,
  SportsSoccer,
  Subscriptions,
  Toll,
  Train,
  TrendingUp,
  WaterDrop,
  VolunteerActivism,
  Wifi,
  Work,
} from '@mui/icons-material';
import type { SvgIconProps } from '@mui/material/SvgIcon';
import type { ComponentType } from 'react';

export const DEFAULT_CATEGORY_ICON_KEY = 'category';

export const CATEGORY_ICON_OPTIONS = [
  { key: 'category', label: 'Category' },
  { key: 'home', label: 'Home' },
  { key: 'rent', label: 'Rent' },
  { key: 'groceries', label: 'Groceries' },
  { key: 'restaurant', label: 'Restaurant' },
  { key: 'fast_food', label: 'Fast food' },
  { key: 'coffee', label: 'Coffee' },
  { key: 'travel', label: 'Travel' },
  { key: 'car', label: 'Car' },
  { key: 'health', label: 'Health' },
  { key: 'fitness', label: 'Fitness' },
  { key: 'sports', label: 'Sports' },
  { key: 'debts', label: 'Debts' },
  { key: 'banking', label: 'Banking' },
  { key: 'cash', label: 'Cash' },
  { key: 'investments', label: 'Investments' },
  { key: 'education', label: 'Education' },
  { key: 'parking', label: 'Parking' },
  { key: 'freelancing', label: 'Freelancing' },
  { key: 'taxes', label: 'Taxes' },
  { key: 'auto_maintenance', label: 'Auto maintenance' },
  { key: 'repairs', label: 'Repairs' },
  { key: 'home_repairs', label: 'Home repairs' },
  { key: 'fines', label: 'Fines' },
  { key: 'tolls', label: 'Tolls' },
  { key: 'gifts', label: 'Gifts' },
  { key: 'charity', label: 'Charity' },
  { key: 'pets', label: 'Pets' },
  { key: 'entertainment', label: 'Entertainment' },
  { key: 'music', label: 'Music' },
  { key: 'games', label: 'Games' },
  { key: 'hotel', label: 'Hotel' },
  { key: 'public_transport', label: 'Public transport' },
  { key: 'utilities', label: 'Utilities' },
  { key: 'internet', label: 'Internet' },
  { key: 'subscriptions', label: 'Subscriptions' },
  { key: 'phone', label: 'Phone' },
  { key: 'fuel', label: 'Fuel' },
  { key: 'pharmacy', label: 'Pharmacy' },
  { key: 'childcare', label: 'Childcare' },
  { key: 'shopping', label: 'Shopping' },
  { key: 'clothing', label: 'Clothing' },
] as const;

export type CategoryIconKey = (typeof CATEGORY_ICON_OPTIONS)[number]['key'];

const CATEGORY_ICON_COMPONENTS: Record<string, ComponentType<SvgIconProps>> = {
  category: CategoryIconGlyph,
  home: Home,
  rent: Apartment,
  groceries: LocalGroceryStore,
  restaurant: Restaurant,
  fast_food: Fastfood,
  coffee: LocalCafe,
  travel: Flight,
  car: DirectionsCar,
  health: LocalHospital,
  fitness: FitnessCenter,
  sports: SportsSoccer,
  debts: CreditCard,
  banking: AccountBalance,
  cash: AccountBalanceWallet,
  investments: TrendingUp,
  education: School,
  parking: LocalParking,
  freelancing: Work,
  taxes: ReceiptLong,
  auto_maintenance: DirectionsCar,
  repairs: Build,
  home_repairs: HomeRepairService,
  fines: Gavel,
  tolls: Toll,
  gifts: CardGiftcard,
  charity: VolunteerActivism,
  pets: Pets,
  entertainment: Movie,
  music: MusicNote,
  games: SportsEsports,
  hotel: Hotel,
  public_transport: Train,
  utilities: WaterDrop,
  internet: Wifi,
  subscriptions: Subscriptions,
  phone: Phone,
  fuel: LocalGasStation,
  pharmacy: LocalPharmacy,
  childcare: ChildCare,
  shopping: ShoppingCart,
  clothing: Checkroom,
};

export const getCategoryIconComponent = (iconKey?: string | null) =>
  CATEGORY_ICON_COMPONENTS[iconKey ?? ''] ??
  CATEGORY_ICON_COMPONENTS[DEFAULT_CATEGORY_ICON_KEY];

export const getCategoryIconLabel = (iconKey?: string | null) =>
  CATEGORY_ICON_OPTIONS.find((option) => option.key === iconKey)?.label ??
  CATEGORY_ICON_OPTIONS[0].label;

export const CategoryIcon = ({
  iconKey,
  ...props
}: { iconKey?: string | null } & SvgIconProps) => {
  const Icon = getCategoryIconComponent(iconKey);
  return <Icon {...props} />;
};
