import {
  AccountBalance,
  AccountBalanceWallet,
  Apartment,
  Build,
  CardGiftcard,
  Category as CategoryIconGlyph,
  Checkroom,
  ChildCare,
  CreditCard,
  DirectionsCar,
  Fastfood,
  FitnessCenter,
  Flight,
  Gavel,
  Home,
  HomeRepairService,
  Hotel,
  LocalCafe,
  LocalGasStation,
  LocalGroceryStore,
  LocalHospital,
  LocalParking,
  LocalPharmacy,
  Movie,
  MusicNote,
  Pets,
  Phone,
  ReceiptLong,
  Restaurant,
  School,
  ShoppingCart,
  SportsEsports,
  SportsSoccer,
  Subscriptions,
  Toll,
  Train,
  TrendingUp,
  WaterDrop,
  VolunteerActivism,
  Wifi,
  Work,
  CarRepair,
  BakeryDining,
  BusinessCenter,
  ConfirmationNumber,
  Devices,
  Event,
  LiveTv,
  LocalBar,
  LocalLaundryService,
  MenuBook,
  Payments,
  Shield,
  Spa,
  Compost,
  Recycling,
  PedalBike,
  TwoWheeler,
  BeachAccess,
  Waves,
  Pool,
  Surfing,
  HolidayVillage,
  Umbrella,
  Cottage,
  Villa,
  Kitesurfing,
  Wc,
  Diversity2,
  People,
  FamilyRestroom,
  Luggage,
} from '@mui/icons-material';
import type { SvgIconProps } from '@mui/material/SvgIcon';
import type { ComponentType } from 'react';

export const DEFAULT_CATEGORY_ICON_KEY = 'category';

export const CATEGORY_ICON_OPTIONS = [
  { key: 'category', label: 'Category' },
  { key: 'home', label: 'Home' },
  { key: 'rent', label: 'Rent' },
  { key: 'groceries', label: 'Groceries' },
  { key: 'restaurant', label: 'Restaurant' },
  { key: 'fast_food', label: 'Fast food' },
  { key: 'coffee', label: 'Coffee' },
  { key: 'travel', label: 'Travel' },
  { key: 'car', label: 'Car' },
  { key: 'health', label: 'Health' },
  { key: 'fitness', label: 'Fitness' },
  { key: 'sports', label: 'Sports' },
  { key: 'debts', label: 'Debts' },
  { key: 'banking', label: 'Banking' },
  { key: 'cash', label: 'Cash' },
  { key: 'investments', label: 'Investments' },
  { key: 'education', label: 'Education' },
  { key: 'parking', label: 'Parking' },
  { key: 'freelancing', label: 'Freelancing' },
  { key: 'taxes', label: 'Taxes' },
  { key: 'auto_maintenance', label: 'Auto maintenance' },
  { key: 'repairs', label: 'Repairs' },
  { key: 'home_repairs', label: 'Home repairs' },
  { key: 'fines', label: 'Fines' },
  { key: 'tolls', label: 'Tolls' },
  { key: 'gifts', label: 'Gifts' },
  { key: 'charity', label: 'Charity' },
  { key: 'pets', label: 'Pets' },
  { key: 'entertainment', label: 'Entertainment' },
  { key: 'music', label: 'Music' },
  { key: 'games', label: 'Games' },
  { key: 'hotel', label: 'Hotel' },
  { key: 'public_transport', label: 'Public transport' },
  { key: 'utilities', label: 'Utilities' },
  { key: 'internet', label: 'Internet' },
  { key: 'subscriptions', label: 'Subscriptions' },
  { key: 'phone', label: 'Phone' },
  { key: 'fuel', label: 'Fuel' },
  { key: 'pharmacy', label: 'Pharmacy' },
  { key: 'childcare', label: 'Childcare' },
  { key: 'shopping', label: 'Shopping' },
  { key: 'clothing', label: 'Clothing' },
  { key: 'salary', label: 'Salary' },
  { key: 'insurance', label: 'Insurance' },
  { key: 'personal_care', label: 'Personal care' },
  { key: 'books', label: 'Books' },
  { key: 'electronics', label: 'Electronics' },
  { key: 'streaming', label: 'Streaming' },
  { key: 'events', label: 'Events' },
  { key: 'tickets', label: 'Tickets' },
  { key: 'laundry', label: 'Laundry' },
  { key: 'bar', label: 'Bar' },
  { key: 'bakery', label: 'Bakery' },
  { key: 'business', label: 'Business' },
  { key: 'compost', label: 'Compost' },
  { key: 'recycling', label: 'Recycling' },
  { key: 'pedal_bike', label: 'Pedal bike' },
  { key: 'two_wheeler', label: 'Two-wheeler' },
  { key: 'beach', label: 'Beach' },
  { key: 'waves', label: 'Waves' },
  { key: 'pool', label: 'Pool' },
  { key: 'surfing', label: 'Surfing' },
  { key: 'holiday_village', label: 'Holiday village' },
  { key: 'umbrella', label: 'Umbrella' },
  { key: 'cottage', label: 'Cottage' },
  { key: 'villa', label: 'Villa' },
  { key: 'kitesurfing', label: 'Kitesurfing' },
  { key: 'wc', label: 'WC' },
  { key: 'diversity', label: 'Diversity' },
  { key: 'people', label: 'People' },
  { key: 'family', label: 'Family' },
  { key: 'luggage', label: 'Luggage' },
] as const;

export type CategoryIconKey = (typeof CATEGORY_ICON_OPTIONS)[number]['key'];

const CATEGORY_ICON_COMPONENTS: Record<string, ComponentType<SvgIconProps>> = {
  category: CategoryIconGlyph,
  home: Home,
  rent: Apartment,
  groceries: LocalGroceryStore,
  restaurant: Restaurant,
  fast_food: Fastfood,
  coffee: LocalCafe,
  travel: Flight,
  car: DirectionsCar,
  health: LocalHospital,
  fitness: FitnessCenter,
  sports: SportsSoccer,
  debts: CreditCard,
  banking: AccountBalance,
  cash: AccountBalanceWallet,
  investments: TrendingUp,
  education: School,
  parking: LocalParking,
  freelancing: Work,
  taxes: ReceiptLong,
  auto_maintenance: CarRepair,
  repairs: Build,
  home_repairs: HomeRepairService,
  fines: Gavel,
  tolls: Toll,
  gifts: CardGiftcard,
  charity: VolunteerActivism,
  pets: Pets,
  entertainment: Movie,
  music: MusicNote,
  games: SportsEsports,
  hotel: Hotel,
  public_transport: Train,
  utilities: WaterDrop,
  internet: Wifi,
  subscriptions: Subscriptions,
  phone: Phone,
  fuel: LocalGasStation,
  pharmacy: LocalPharmacy,
  childcare: ChildCare,
  shopping: ShoppingCart,
  clothing: Checkroom,
  salary: Payments,
  insurance: Shield,
  personal_care: Spa,
  books: MenuBook,
  electronics: Devices,
  streaming: LiveTv,
  events: Event,
  tickets: ConfirmationNumber,
  laundry: LocalLaundryService,
  bar: LocalBar,
  bakery: BakeryDining,
  business: BusinessCenter,
  compost: Compost,
  recycling: Recycling,
  pedal_bike: PedalBike,
  two_wheeler: TwoWheeler,
  beach: BeachAccess,
  waves: Waves,
  pool: Pool,
  surfing: Surfing,
  holiday_village: HolidayVillage,
  umbrella: Umbrella,
  cottage: Cottage,
  villa: Villa,
  kitesurfing: Kitesurfing,
  wc: Wc,
  diversity: Diversity2,
  people: People,
  family: FamilyRestroom,
  luggage: Luggage,
};

export const getCategoryIconComponent = (iconKey?: string | null) =>
  CATEGORY_ICON_COMPONENTS[iconKey ?? ''] ??
  CATEGORY_ICON_COMPONENTS[DEFAULT_CATEGORY_ICON_KEY];

export const getCategoryIconLabel = (iconKey?: string | null) =>
  CATEGORY_ICON_OPTIONS.find((option) => option.key === iconKey)?.label ??
  CATEGORY_ICON_OPTIONS[0].label;

export const CategoryIcon = ({
  iconKey,
  ...props
}: { iconKey?: string | null } & SvgIconProps) => {
  const Icon = getCategoryIconComponent(iconKey);
  return <Icon {...props} />;
};
