<?php
/* CONSTANTS */
define("DEFAULT_GROUP_NAME","ENSO");
define("DEFAULT_ROLE_NAME", "Regular");
define("DEFAULT_VACATIONS_VAC_TYPE", "Férias");
define("DEFAULT_VAC_REQ_COMMENT", "Sem Comentários");
define("DEFAULT_REQ_STATUS_APPROVED", "Aprovado");
define("DEFAULT_REQ_STATUS_DENIED", "Negado");
define("DEFAULT_REQ_STATUS_PENDING", "Pendente");
define("DEFAULT_REQ_STATUS_CANCELLED", "Cancelado");
define("DEFAULT_REQ_STATUS_PENDING_CANCELATION", "Pedido de Cancelamento");

/* NOTIFICATION TEMPLATES */
define("NOTIF_NEW_VAC_REQ_ADDED", "NOTIF_NEW_VAC_REQ_ADDED");
define("NOTIF_VAC_REQ_STATUS_UPDATED", "NOTIF_VAC_REQ_STATUS_UPDATED");
define("NOTIF_NEW_TASK_ADDED", "NOTIF_NEW_TASK_ADDED");
define("NOTIF_VAC_REQ_CANCELATION_REQUEST", "NOTIF_VAC_REQ_CANCELATION_REQUEST");

