// Theming
export enum ColorGradient {
  Red = 'red-gradient',
  Blue = 'blue-gradient',
  Green = 'green-gradient',
  Orange = 'orange-gradient',
  DarkGray = 'dark-gray-gradient',
  LightGray = 'light-gray-gradient',
  Purple = 'purple-gradient',
  Pink = 'pink-gradient',
  DarkBlue = 'dark-blue-gradient',
  Brown = 'brown-gradient',
  LightGreen = 'light-green-gradient',
  DarkRed = 'dark-red-gradient',
  Yellow = 'yellow-gradient',
  Roseanna = 'roseanna-gradient',
  Mauve = 'mauve-gradient',
  Lush = 'lush-gradient',
  PaleWood = 'pale-wood-gradient',
  Aubergine = 'aubergine-gradient',
  OrangeCoral = 'orange-coral-gradient',
  Decent = 'decent-gradient',
  Dusk = 'dusk-gradient',
  Dull = 'dull-gradient',
  AquaColor = 'aqua-color',
  BlueColor = 'blue-color',
  GreenColor = 'green-color',
  TealColor = 'teal-color',
  CoralColor = 'coral-color',
  YellowColor = 'yellow-color',
  OrangeColor = 'orange-color',
  PaleColor = 'pale-color',
  PinkColor = 'pink-color',
  BrownColor = 'brown-color',
  RedColor = 'red-color',
  None = '',
}
